### ISSUE TITLE
fabric-forge does not start and crashes with "Error when validating..." errors

### ISSUE THREAD

**Issue by grandmore** [fabric8io/fabric8#6110]
I have installed the `apps` onto a clean GKE hosted kubernetes cluster of 2 nodes using `gofabric8 deploy -y`

I first used the [installation information in the docs](http://fabric8.io/guide/getStarted/gke.html) and created google hosted kubernetes cluster using the kubctl command `kc create -f http://central.maven.org/maven2/io/fabric8/apps/console-kubernetes/2.2.154/console-kubernetes-2.2.154-kubernetes.json` I used the latest version of 2.2.165 instead of the docs version that refers to `2.2.104`

However the fabric-forge pod keeps crashing.

#### Here is the log file. 
----------------------
Checking *.war in /maven
Linking /maven/ROOT.war --> /opt/jetty/webapps/ROOT.war
Running Jetty: 
I> No access restrictor found, access to all MBean is allowed
Jolokia: Agent started with URL http://10.0.0.8:8778/jolokia/
2016-06-25 20:52:23.441:INFO:ifasjoejs.Server:jetty-8.y.z-SNAPSHOT
2016-06-25 20:52:23.481:INFO:ifasjoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9779
2016-06-25 20:52:24.154:INFO::main: Logging initialized @1052ms
2016-06-25 20:52:24.243:WARN:oejs.HomeBaseWarning:main: This instance of Jetty is not running from a separate {jetty.base} directory, this is not recommended.  See documentation at http://www.eclipse.org/jetty/documentation/current/startup.html
2016-06-25 20:52:24.615:INFO:oejs.Server:main: jetty-9.3.2.v20150730
2016-06-25 20:52:24.642:INFO:oejdp.ScanningAppProvider:main: Deployment monitor [file:///opt/jetty-distribution-9.3.2.v20150730/webapps/] at interval 1
WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
WELD-000900: 2.3.4 (Final)
Jun 25, 2016 8:52:31 PM org.apache.deltaspike.core.util.ProjectStageProducer initProjectStage
INFO: Computed the following DeltaSpike ProjectStage: Production
WELD-001208: Error when validating jar:file:/tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-1025774567379228776.dir/webapp/WEB-INF/lib/fabric8-forge-core-2.2.208.jar!/META-INF/beans.xml@22 against xsd. cvc-complex-type.3.2.2: Attribute 'version' is not allowed to appear in element 'beans'.
WELD-001208: Error when validating jar:file:/tmp/jetty-0.0.0.0-8080-ROOT.war-_-any-1025774567379228776.dir/webapp/WEB-INF/lib/fabric8-forge-core-2.2.208.jar!/META-INF/beans.xml@24 against xsd. cvc-complex-type.2.4.a: Invalid content was found starting with element 'scan'. One of '{"http://java.sun.com/xml/ns/javaee":interceptors, "http://java.sun.com/xml/ns/javaee":decorators, "http://java.sun.com/xml/ns/javaee":alternatives, WC[##other:"http://java.sun.com/xml/ns/javaee"]}' is expected.
WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
WELD-000411: Observer method [BackedAnnotatedMethod] public io.fabric8.cdi.Fabric8Extension.processAnnotatedType(@Observes ProcessAnnotatedType<R>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.exclude.extension.ExcludeExtension.vetoBeans(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.interceptor.GlobalInterceptorExtension.promoteInterceptors(@Observes ProcessAnnotatedType, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WELD-000411: Observer method [BackedAnnotatedMethod] protected org.apache.deltaspike.core.impl.message.MessageBundleExtension.detectInterfaces(@Observes ProcessAnnotatedType) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WELD-ENV-001200: Jetty 7.2+ detected, CDI injection will be available in Servlets and Filters. Injection into Listeners should work on Jetty 9.1.1 and newer.
WELD-001125: Illegal bean type java.util.Comparator<org.jboss.forge.addon.resource.Resource<?>> ignored on [EnhancedAnnotatedTypeImpl] private static  class org.jboss.forge.addon.resource.AbstractResource$FQNResourceComparator
WELD-001125: Illegal bean type java.util.Comparator<java.lang.Class<?>> ignored on [EnhancedAnnotatedTypeImpl] public  class org.jboss.forge.addon.resource.util.RelatedClassComparator
WELD-001473: javax.enterprise.inject.spi.Bean implementation org.apache.cxf.cdi.CdiBusBean@53dacd14 declared a normal scope but does not implement javax.enterprise.inject.spi.PassivationCapable. It won't be possible to inject this bean into a bean with a passivating scope (@SessionScoped, @ConversationScoped). This can be fixed by assigning the Bean implementation a unique id by implementing the PassivationCapable interface.
Jun 25, 2016 8:52:36 PM io.fabric8.forge.rest.main.ForgeInitialiser <init>
INFO: Logging to JUL to test the configuration
initialising furnace with folder: /forge-addon-repo
Found 45 addon files in directory: /forge-addon-repo
Jun 25, 2016 8:52:37 PM org.jboss.forge.furnace.impl.FurnaceImpl start
INFO: Furnace [2.23.5.Final] starting.
Jun 25, 2016 8:52:43 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 2.3.2 (Final)
Jun 25, 2016 8:52:43 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 5.3.0.Alpha1
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jun 25, 2016 8:52:43 PM org.jboss.weld.xml.BeansXmlHandler error
WARN: WELD-001208: Error when validating jar:file:/forge-addon-repo/io-fabric8-forge-funktion-2-2-208/funktion-2.2.208-forge-addon.jar!/META-INF/beans.xml@2 against xsd. cvc-complex-type.4: Attribute 'bean-discovery-mode' must appear on element 'beans'.
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-1.b16.el7_1.x86_64/jre/lib/rt.jar: error reading zip file
/opt/jetty/bin/deploy-and-run.sh: line 12:    10 Killed                  /usr/bin/env bash /opt/jetty/bin/jetty.sh run

**Comment by christian-posta** [comment]
Wonder if what you're seeing is related to what I'm seeing?

https://groups.google.com/forum/#!topic/fabric8/-psStDKi5Ow
https://gist.github.com/christian-posta/e8ae480930ce0fac202ea31b3bace296

**Comment by jstrachan** [comment]
@grandmore wow this took a while to track down. Just about to cut a release to fix this issue. 

Here's a quick workaround if you want to try it out on your GKE environment: type
```
kubectl edit rc fabric8-forge
```
then scroll down to the line that says `memory: 512Mi` and change it to `memory: '0'`. 

Then kill the old failing fabric8-forge pod; a new pod should be created without this 512Mi limit which should startup fine without getting killed by GKE :) 

Sorry about that! This apparently innocent change slipped through our CD process (we'll hopefully fix that soon too!!!).

There should be a new release of fabric8-forge in 2-4 hours time in which case deleting the fabric8-forge RC and re-running `gofabric8` should install the new release (2.2.209) of fabric8-forge with this bug removed. 

Sorry about that!

**Comment by grandmore** [comment]
Thanks for the fix.

**Comment by jstrachan** [comment]
FWIW the 2.2.209 release of fabric8-forge should be out within the hour; so next time you run `gofabric8 deploy` it'll pick that one up
