### ISSUE TITLE
FabricMQ unable to find AMQ broker in 2.2.19

### ISSUE THREAD

**Issue by Scyta1e** [fabric8io/fabric8#4599]
Running docker 1.6.2 / OS Origin v3 1.0.3 natively on RHEL 7.1:

NAME                         READY     STATUS    RESTARTS   AGE
amqbroker-sj1jy              1/1       Running   0          3m
api-registry-mz1yp           1/1       Running   0          19m
docker-registry-1-q32my      1/1       Running   0          1h
elasticsearch-a98gk          2/2       Running   0          19m
fabric8-http-gateway-ed1oj   1/1       Running   0          19m
fabric8-l3ua6                1/1       Running   0          1h
fabric8mq-skylw              1/1       Running   0          1m
kibana-c9lro                 2/2       Running   1          19m
router-1-dt1ud               1/1       Running   0          1h

oc logs fabric8mq-skylw shows every polling interval:

Failed to pollBrokers
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.headers()Lorg/jboss/netty/handler/codec/http/HttpHeaders;

IRC Session:
[22:31] <jdyson> Scyta1e, looks like a bug.... can you raise an issu eat https://github.com/fabric8io/fabric8? Looks like a possible conflict in netty used in both the gateway & in the kubernetes client

**Comment by jimmidyson** [comment]
This is a conflict between the netty versions in the kubernetes client (netty 3) & fabric8 mq (netty 4). Might think about shading the netty3 dependencies into the client to get around this problem that others may face as well.

**Comment by Scyta1e** [comment]
Can confirm it works in 2.2.16
