### ISSUE TITLE
kubernetes-assertions - Does not work with assertj-core 2.6.0

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8#6863]
When having these JARs on my classpath
```
[INFO] +- io.fabric8:kubernetes-assertions:jar:2.2.210:test
[INFO] |  +- io.fabric8:kubernetes-api:jar:2.2.210:test
[INFO] |  |  +- io.fabric8:openshift-client:jar:2.2.14:test
[INFO] |  |  +- org.json:json:jar:20140107:test
[INFO] |  |  \- dnsjava:dnsjava:jar:2.1.8:test
[INFO] |  +- io.fabric8:kubernetes-client:jar:2.2.14:test
[INFO] |  |  +- io.fabric8:kubernetes-model:jar:1.0.72:test
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.8:test
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  +- io.fabric8:fabric8-utils:jar:2.2.210:test
[INFO] |  \- org.assertj:assertj-core:jar:2.6.0:test
```

Then notice `org.assertj:assertj-core:jar:2.6.0:test` and when I run the test it fails with
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.789 sec <<< FAILURE! - in com.camelinaction.PodStartedKT
testPodStarted(com.camelinaction.PodStartedKT)  Time elapsed: 0.678 sec  <<< ERROR!
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/util/List;)Lorg/assertj/core/api/AbstractListAssert;
	at com.camelinaction.PodStartedKT.testPodStarted(PodStartedKT.java:29)
```

But if I go back to version 2.4.1, then it works.

**Comment by davsclaus** [comment]
btw assertj-core is has also version 3.x
